global:
  # 日历名称
  calendar_name: example-lunar-birthday

  # timezone 为 iCal 的全局配置
  timezone: Asia/Shanghai

  # bool: true | false
  # 配置 startdate 是否是 出生日期
  birthday: true
  lunar_birthday: true

  # VEVENT 事件的开始时间, 格式为 %H:%M:%S
  # 时间为当地时间, 写入 iCal 时会转换为 UTC
  # 注意用双引号括起来, 防止 YAML 自动格式转换
  event_time: "10:00:00"
  # VEVENT 事件时长, 单位小时
  event_duration: 2

  # 分别提前 x 天创建提醒时间
  reminders: [1, 3, 7]
  # VEVENT 事件参会人
  attendees:
    - charlie.zhang@example.com
    - delta.lee@example.com

  # 农历生日时间最大年龄
  max_ages: 100
  # 降临日 最大天数
  max_days: 36000
  # 降临日 事件间隔天数
  interval: 1000

  # pastebin
  # https://komj.uk/api
  pastebin: false
  pastebin_url: https://komj.uk
  pastebin_expiration: ""
  pastebin_name: ""
  pastebin_password: ""

# startdate 为过去的某个日期, 格式为 %Y-%m-%d
startdate_list:
  - username: 张三
    startdate: 1989-06-03
    birthday: true
    lunar_birthday: true

  - username: 李四
    startdate: 2006-02-01
    birthday: true
    lunar_birthday: true
